### ISSUE TITLE
Create Report Info Graphic Mockup

### ISSUE THREAD

**Issue by nathanbunker** [immregistries/mqe#100]
Create a mockup of a single page PDF that shows what we want to have for an MQE report.

**Comment by JoshHull** [comment]
This task is partially done.  I'll post a picture of the current thinking.  We discussed this at the end of the sprint day, and decided on these high level goals: 

- A single indicator for quality assessment.  This will be an aggregate score based on all the sections.   In the mockup we used a grading system - A/B/C etc. 
- Sections for concise views into the biggest issues in each concept (issues, codes, vaccines)

**Comment by JoshHull** [comment]
![image](https://user-images.githubusercontent.com/10420985/46805415-fb1f6e00-cd32-11e8-8e44-c74d370f90b1.png)

**Comment by nathanbunker** [comment]
Made progress on putting the scoring together. Discussed with Josh Hull and he is now going to take over and make a mockup. Here is what has been decided so far:

**Scoring System**

The total score for the report will be 1000, that is the highest score that can be awarded in the report. This score is meant to be expressive, good quality will start somewhere between 700 and 800 points. All points awarded or taken away in the report will be in whole increments. This is to simplify the scoring system for those that read it. Currently proposing that the final score be categorized into one of these categories: 

- Meets
- Almost Meets
- Does Not Meet

Take a look at the icons used by AART for inspiration: http://florence.immregistries.org/aart/adminReportDiagramGeneratorDemoServlet

**Comment by nathanbunker** [comment]
**Areas to Measure**

We have identified four major areas to measure:
- Errors
- Warnings
- Patient and Vaccination Fields
- Vaccine Coverage

![image](https://user-images.githubusercontent.com/122847/49898014-00716580-fe15-11e8-832f-f6ed82a0345b.png)

The errors and warnings sections will subtract from the overall score. The other sections will add to the score. The exact weight of these sections has not been set, but in general the size of the image above suggests their relative weights.

**Comment by nathanbunker** [comment]
**Errors and Warnings**

In the original DQA these were set by creating a threshold of how many errors or warnings we expected by the count of messages. The idea is that a certain rate of errors is acceptable. In the new system we are now thinking it should be independent of the number of messages sent and instead should depend on the number of days that the report covers. The ideas is that the impact of errors are independent of the number of messages sent. We want all sites to get to zero, and if there are more than zero the amount of work is the same whether it's a large hospital system or small practice. Additionally larger sites, which could have more errors, have more technical expertise and should be able to reduce errors to very low levels. So we thing that setting a threshold of something like no more than a certain number of errors per interface per day and then measuring from there.

**Comment by nathanbunker** [comment]
**Vaccine Coverage**

Looking at the graph above that shows the vaccine groups that were found in the file, the following calculation was made: 

![image](https://user-images.githubusercontent.com/122847/49898241-b8067780-fe15-11e8-83c6-b3eddb9e95ac.png)

The total number of groups is calculated by the number of groups that were expected. You can count all the ones that are green, or the ones that are red and have a 0 in the. (Skip the ones that are red with a number in them, these were not expected.). This gives you 24.

Then total points possible for this section is divided by the groups and rounded up. This gives us the points per group included. 

Then points are given for each section that was expected and there was at least one vaccination sent. No points are given if there were none sent. And half the points are taken away if a vaccine was sent that wasn't expected and a full amount of points taken away if the sent vaccine was not possible to have been given to this age.

**Comment by nathanbunker** [comment]
**Patient and Vaccination Fields**

This is very similar to Vaccine Coverage. But first each field has to be identified and a target level defined. This level is the minimum that needs to be achieved by the IIS. Then if it meets the threshold it is counted as passing. The total score is simply the number that are passing for both patient and vaccination fields.

![image](https://user-images.githubusercontent.com/122847/49898441-4aa71680-fe16-11e8-8e6c-d76dc1b70049.png)

The count will be the number of times the field is given a valid value. Invalid values, such as bad dob, or unrecognized codes for coded values will not count.

**Comment by nathanbunker** [comment]
**Improve Your Score**

The reports should use the scoring system to identify which areas could be improved that would have the biggest impact on the score. This section could give specific advice on which errors to fix or what fields need to be included. 

The report might also show if they are getting better or worse when compared with other reports.

**Comment by nathanbunker** [comment]
While this report could be generated for one day's worth of data, it really only makes sense to generate for a week or a month. Other time periods have problems. Shorter than a week would be inconsistent as vaccine practice varies by day. Longer than a week would not show trends very well. Weekly and/or monthly seem to be the most sensible division points.

**Comment by nathanbunker** [comment]
[Report Card.xlsx](https://github.com/immregistries/mqe/files/2673528/Report.Card.xlsx)

**Comment by JoshHull** [comment]
We put some energy into this for this month's sprint. I have attached the documents we created. I'll also attach some notes we took about the on-boarding process from Iris.
 
[MQE Reporting.pdf](https://github.com/immregistries/mqe/files/3486916/MQE.Reporting.pdf)

**Comment by JoshHull** [comment]
[MQE Integration Report.zip](https://github.com/immregistries/mqe/files/3487879/MQE.Integration.Report.zip)

**Comment by nathanbunker** [comment]
The mockup has been created. This task is probably closed now.

**Comment by nathanbunker** [comment]
Closing this for now. But may want to look at this in the future if we want to remember.
