### ISSUE TITLE
Increase Efficiency In Processing Messages

### ISSUE THREAD

**Issue by jnarine** [immregistries/mqe#105]
Look into implementing PostgreSQL database or changing option(s) within current H2 database, so the MQETool can handle more messages.

We are looking to resolve the current memory limitations the MQETool has when submitting large amounts of messages (100k+).

**Comment by jnarine** [comment]
@JoshHull

**Comment by JoshHull** [comment]
Hey @jnarine, can you document the steps to replicate this issue, and what errors or messages you see?

**Comment by JoshHull** [comment]
From these docs: http://h2database.com/html/advanced.html#limits_limitations

Main memory requirements: The larger the database, the more main memory is required. With the current storage mechanism (the page store), the minimum main memory required is around 1 MB for each 8 GB database file size.

@jnarine I'm curious how big your database file gets when you run out of memory.  can you post that?

**Comment by JoshHull** [comment]
This seems like a promising option: 

> nioMemFS: stores data outside of the VM's heap - useful for large memory DBs without incurring GC costs.
