### ISSUE TITLE
Detection Documentation Enhancements

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#109]
[Overview]
Documentation was created with code to be displayed in the UI as well as available for download as PDF. Consider improvements to display as well as ability to expand/collapse/search. Consider filtering and improving appearance PDF - current display is for ALL possible elements, may limit to just those things that are detected. May also want to add additional information to the summary/description.

**Comment by nathanbunker** [comment]
This is old and has either been completed or is not relevant.
