### ISSUE TITLE
Segment Highlights wrong segment

### ISSUE THREAD

**Issue by katelyndavis** [immregistries/mqe#117]
[OVERVIEW]
![image](https://user-images.githubusercontent.com/37371748/46767281-89074480-ccb2-11e8-9676-499e36351c7b.png)
Empty segments are not highlighted properly. I'm thinking there is an intentional blank space for each empty segment value but they are being place in the last non-empty value segment instead of their proper location.

[REQUIREMENT]
Its expected that empty values should be highlighted in the proper message location.

[DEV NOTES]

**Comment by JoshHull** [comment]
I found the problem with this.  It was an issue with finding the length of an empty value and then trying to substring using that length (which doesn't grab the next separator). 

I've pushed out a bug fix.
