### ISSUE TITLE
Add SmartyStreets/Address cleansing to validation

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#32]
[OVERVIEW]
Add support for address cleansing that supports either the MCIR model and   Smartystreets. Consistent API in the validator that can be implemented as   either. Built in for Smartystreets and MCIR would make their own for their   use. API would support the union/intersection of these solutions.             

[REQUIREMENTS]
[Break it down into components, but it is still oriented around business   requirements, UI/DBB/Fields]      Must call out to Smarty   Streets      There are more requirements but they need to be determined.             

[DEV NOTES]
[where devs note stuff to each other to give help on how to get   started]            

[TESTING]
[how to verify it's done.  A lot of it   is repeat of the req section, and may refer to it]

**Comment by JoshHull** [comment]
I've added a basic implementation for SmartyStreets, and a way to change the implementation easily in the class AddressCleanserFactory.java

With my changes, there's a new config file that will be included with MQE called **validation.properties**.  In that file, you can turn on or off address cleansing, and you can provide your smarty streets  key/id. 

There are validations for the patient address, NK address, and Guardian address. 

If you turn on validation, and put in your key/id, you can see it in action in the MQE demo.  You will see a message in the ACK if the patient address is bad.

**Comment by JoshHull** [comment]
I just submitted pull requests to bring my changes into the 2018.4 branch

**Comment by nathanbunker** [comment]
See issue #59 with a follow on ticket
