### ISSUE TITLE
Codebase XML file should be easy to update

### ISSUE THREAD

**Issue by nathanbunker** [immregistries/mqe#39]
[OVERVIEW]
The Codebase XML file contains information about the codes and concepts used by the MQE and will updated by the CDC and eventually also by the MQE community several times a year. When these updates are made the user should be able to pull them down from the github MQE site and load them into a locally running copy. 

[REQUIREMENT]
The codebase XML file should be externally referenced by MQE. The current version of the codebase XML file should be available on the MQE download site. The user may download the most recent codebase XML file and replace the version sitting on their local system. After restarting MQE the new codeset should take affect. 

[DEV NOTES]
There will then be two copies of the codebase XML, on in the zip of MQE software and one by itself in MQE for easy download. We'll make a wiki entry for it as well, so it's easy for someone to download. We might also want to make the XML file a zip file itself, that will make downloads faster. 

[TESTING]
You will need to make two versions of the codebase XML, one that is correct and one that is missing a CVX code, such as '03'. Then submit a message with that vaccination to the MQE for processing. In one time use the MQE as it is installed, and verify the message is accepted without problems. Then update the codebase XML with the defective XML and restart it. Run the import again and verify that it doesn't recognize the code. This confirms that updating the file is possible.

**Comment by michellefbarber** [comment]
https://codebase-consensus.firebaseapp.com/

**Comment by nathanbunker** [comment]
Looks like this is probably working already. The debugging code says that it is finding the Compiled.xml and reading it from the local file. Need to also change the installation process so that it's in the zip file and not the war.
