### ISSUE TITLE
Reporting Affirmatives

### ISSUE THREAD

**Issue by HossamT** [immregistries/mqe#40]
[OVERVIEW]
The tool should report what issues were evaluated and passed, this will allow getting more sense of what was evaluated on the record. This requirement is particularly important for the integration of the MQE in the Data At Rest project in order to be able to calculate percentages of issues related to the whole sample of patient records.

**Comment by nathanbunker** [comment]
I don't remember how the object is formatted, but we probably can just have a count, and a countNegative. We can also probably put the countTotal, although that might be redundant.

**Comment by nathanbunker** [comment]
This class might be the area you are looking at: org.immregistries.dqa.validator.issue.VxuField

**Comment by michellefbarber** [comment]
Closed per post-sprint review.
