### ISSUE TITLE
Identifying which element an issue was found on.

### ISSUE THREAD

**Issue by HossamT** [immregistries/mqe#41]
[OVERVIEW]
Right now the tool returns a list of ValidationRuleResult, which contains a list of issues. The issues are tied to rules but we can't know exactly on which element each particular issue was found on.
e.g Having a record with vaccinations V1, V2. We should be able to tell if a vaccination-related issue occurred on V1 or V2.

[REQUIREMENT]
Uniquely identifying repeating message elements (Vaccination, Next Of Kin ...)
Adding a field in the ValidationRuleResult where we report the Target ID and Type

**Comment by JoshHull** [comment]
What do you guys do in the NIST validator to indicate the index/order of the Vaccine/Next of Kin?  Do you use an index based on the segment type?  Like, if there are two Vaccines, with a total of four OBX, would you index off the OBX number?  Like 1/2/3/4?  Let's add an example here.  Hold on...

**Comment by JoshHull** [comment]
(example message taken from https://hl7v2-iz-r1.5-testing.nist.gov/iztool/#/cb)

```
MSH|^~\&|NISTEHRAPP|NISTEHRFAC|NISTIISAPP|NISTIISFAC|20150624073733.994-0500||VXU^V04^VXU_V04|NIST-IZ-AD-1.1_Send_V04_Z22|P|2.5.1|||ER|AL|||||Z22^CDCPHINVS|NISTEHRFAC|NISTIISFAC
PID|1||3123^^^NIST-MPI-1^MR||Richardson^Russell^Clint^^^^L|Billington^^^^^^M|20150415|M||1002-5^American Indian or Alaska Native^CDCREC|543 Blount Drive^^Bozeman^MT^59715^USA^P||^PRN^PH^^^406^5557690|||||||||2186-5^Not Hispanic or Latino^CDCREC||N|1|||||N
PD1|||||||||||02^Reminder/recall - any method^HL70215|N|20150624|||A|20150415|20150624
NK1|1|Richardson^Maria^Elizabeth^^^^L|MTH^Mother^HL70063|543 Blount Drive^^Bozeman^MT^59715^USA^P|^PRN^PH^^^406^5557690
NK1|2|Richardson^John^William^^^^L|FTH^Father^HL70063|543 Blount Drive^^Bozeman^MT^59715^USA^P|^PRN^CP^^^406^5558299
ORC|RE|3140^NIST-AA-IZ-2|38766^NIST-AA-IZ-2|||||||7824^Jackson^Lily^Suzanne^^^^^NIST-PI-1^L^^^PRN||654^Thomas^Wilma^Elizabeth^^^^^NIST-PI-1^L^^^MD|||||NISTEHRFAC^NISTEHRFacility^HL70362|
RXA|0|1|20150624||49281-0560-05^Pentacel^NDC|0.5|mL^mL^UCUM||00^New Record^NIP001|7824^Jackson^Lily^Suzanne^^^^^NIST-PI-1^L^^^PRN|^^^NIST-Clinic-1||||526434|20150722|PMC^Sanofi Pasteur^MVX|||CP|A
RXR|C28161^Intramuscular^NCIT|RT^Right Thigh^HL70163
OBX|1|CE|30963-3^Vaccine Funding Source^LN|1|VXC50^Public^CDCPHINVS||||||F|||20150624
OBX|2|CE|64994-7^Vaccine Funding Program Eligibility^LN|2|V04^VFC Eligible - American Indian/Alaska Native^HL70064||||||F|||20150624|||VXC40^per immunization^CDCPHINVS
OBX|3|CE|69764-9^Document Type^LN|3|253088698300017211160720^Polio VIS^cdcgs1vis||||||F|||20150624
OBX|4|DT|29769-7^Date Vis Presented^LN|3|20150624||||||F|||20150624
OBX|5|CE|69764-9^Document Type^LN|4|253088698300006611150402^Haemophilus Influenzae type b VIS^cdcgs1vis||||||F|||20150624
OBX|6|DT|29769-7^Date Vis Presented^LN|4|20150624||||||F|||20150624
OBX|7|CE|69764-9^Document Type^LN|5|253088698300003511070517^Diphtheria/Tetanus/Pertussis (DTaP) VIS^cdcgs1vis||||||F|||20150624
OBX|8|DT|29769-7^Date Vis Presented^LN|5|20150624||||||F|||20150624
ORC|RE|8681^NIST-AA-IZ-2|65138^NIST-AA-IZ-2|||||||7824^Jackson^Lily^Suzanne^^^^^NIST-PI-1^L^^^PRN||654^Thomas^Wilma^Elizabeth^^^^^NIST-PI-1^L^^^MD|||||NISTEHRFAC^NISTEHRFacility^HL70362|
RXA|0|1|20150624||00006-4047-20^RotaTeq^NDC|2.0|mL^mL^UCUM||00^New Record^NIP001|7824^Jackson^Lily^Suzanne^^^^^NIST-PI-1^L^^^PRN|^^^NIST-Clinic-1||||297961|20150916|MSD^Merck and Co., Inc.^MVX|||CP|A
RXR|C38288^Oral^NCIT|
OBX|1|CE|30963-3^Vaccine Funding Source^LN|1|VXC50^Public^CDCPHINVS||||||F|||20150624
OBX|2|CE|64994-7^Vaccine Funding Program Eligibility^LN|2|V04^VFC Eligible - American Indian/Alaska Native^HL70064||||||F|||20150624|||VXC40^per immunization^CDCPHINVS
OBX|3|CE|69764-9^Document Type^LN|3|253088698300019611150415^Rotavirus VIS^cdcgs1vis||||||F|||20150624
OBX|4|DT|29769-7^Date Vis Presented^LN|3|20150624||||||F|||20150624
ORC|RE|7491^NIST-AA-IZ-2|79539^NIST-AA-IZ-2|||||||7824^Jackson^Lily^Suzanne^^^^^NIST-PI-1^L^^^PRN||654^Thomas^Wilma^Elizabeth^^^^^NIST-PI-1^L^^^MD|||||NISTEHRFAC^NISTEHRFacility^HL70362|
RXA|0|1|20150624||00005-1971-01^Prevnar 13^NDC|0.5|mL^mL^UCUM||00^New Record^NIP001|7824^Jackson^Lily^Suzanne^^^^^NIST-PI-1^L^^^PRN|^^^NIST-Clinic-1||||353480|20150729|PFR^Pfizer, Inc^MVX|||CP|A
RXR|C28161^Intramuscular^NCIT|LT^Left Thigh^HL70163
OBX|1|CE|30963-3^Vaccine Funding Source^LN|1|VXC50^Public^CDCPHINVS||||||F|||20150624
OBX|2|CE|64994-7^Vaccine Funding Program Eligibility^LN|2|V04^VFC Eligible - American Indian/Alaska Native^HL70064||||||F|||20150624|||VXC40^per immunization^CDCPHINVS
OBX|3|CE|69764-9^Document Type^LN|3|253088698300015811151105^Pneumococcal Conjugate (PCV13) VIS^cdcgs1vis||||||F|||20150624
OBX|4|DT|29769-7^Date Vis Presented^LN|3|20150624||||||F|||20150624
ORC|RE||31528^NIST-AA-IZ-2|||||||7824^Jackson^Lily^Suzanne^^^^^NIST-PI-1^L^^^PRN|||||||NISTEHRFAC^NISTEHRFacility^HL70362
RXA|0|1|20150416||45^Hep B, unspecified formulation^CVX|999|||01^Historical Administration^NIP001|||||||||||CP|A
ORC|RE||82668^NIST-AA-IZ-2|||||||7824^Jackson^Lily^Suzanne^^^^^NIST-PI-1^L^^^PRN|||||||NISTEHRFAC^NISTEHRFacility^HL70362
RXA|0|1|20150515||45^Hep B, unspecified formulation^CVX|999|||01^Historical Administration^NIP001|||||||||||CP|A

```

**Comment by JoshHull** [comment]
So the question is - do you use absolute indexes or relative?  

The first OBX is the 9th segment in the message so you would tag it as 9.  
Or do you use Relative indexes, so the first OBX is referred to as 1.

**Comment by HossamT** [comment]
We identify issues by path e.g OBX[a]-b[c].d where a,b,c,d are numbers. In addition to the line and column number in the message. We use relative indexes, each segment type has its own count (or instance number as we call it). In this message we have 16 OBX, it means 16 instances of the segment OBX so we identify each one from OBX[1] to OBX[16]

**Comment by JoshHull** [comment]
Dev note:   The code that will change is in dqa-hl7-util project, in the parsing classes.  We know where the data comes from in the parsing process, and we can add it to some sort of messaging metadata collection for the object it parses into. 

For example, in [HL7VaccineParser.java](https://github.com/immregistries/dqa-hl7-util/blob/v2_02_working/src/main/java/org/immregistries/dqa/vxu/parse/HL7VaccineParser.java) on lines 67-81, we figure out the absolute indexes of the segments in the message.   

We can call the method: map.getSegmentOrdinalFromAbsoluteIndex() to get the ordinal number for the segment type (Like, the 5th OBX segment). 

Then we'll have to figure out how we want to store that so that it's available when we execute the validation rules. 

I'm imagining we'd have some kind of MessagingMetadata for each object we build, for example a [DqaVaccination.java](https://github.com/immregistries/dqa-hl7-util/blob/v2_02_working/src/main/java/org/immregistries/dqa/vxu/DqaVaccination.java) object gets built off the ORC/RXA/RXR/OBX segments. We could add a metadata object to that vaccination object to make it available later on.

**Comment by nathanbunker** [comment]
Okay, I've started working on this but need some feedback about whether you both think this is the right direction. 

My idea is to create an object called MetaFieldInfo that will now hold both the value for a particular field and information about where it came from originally. I plan to enable each field to be able return this information if desired. I have done this just for one field to see how it works: birthCounty. This is currently a string, but I propose to keep the same getBirthCounty() and setBirthCounty() function calls but replace the internal String representation with the MetaFieldInfo object. Here is the definition of this object: 

`public class MetaFieldInfo<E> {
  private String valueOriginal = "";
  private E value;
  private int line = 0;
  private int column = 0;
  private ErrorLocation errorLocation = null;`

Not shown here are the getters and setters for the fields. Then I change the getter/setters as follows:

`  public String getBirthCounty() {
    return birthCountyMeta == null ? "" : birthCountyMeta.getValue();
  }

  public void setBirthCounty(String birthCounty) {
    if (birthCountyMeta == null) {
      birthCountyMeta = new MetaFieldInfo<>();
    }
    birthCountyMeta.setValue(birthCounty);
  }`

Now the object acts just at it did before, but you can get/set the meta information like this:

`patient.setBirthCountyMeta(getBirthCounty(map));//PID-11-9 when PID-11-7 is BDL`

This will allow you to get a pre-populated ErrorLocation object which you an drop into the ack response and even associate with the issues. 

Does this look like a good direction?

**Comment by nathanbunker** [comment]
I have created a test case in the validator that takes a message through and demonstrates that the MQE tool can now identify the position of issues it finds. Here is the output:
`MESSAGE: ***********************************************
         MSH|^~\&|ECW|1337-44-01|MCIR|MDCH|20140619191115||VXU^V04|61731|P|2.3.1|||AL
         PID|||00000^^^^MR~111111^^^^WC~22222^^^^SS~33333^^^^MA~44444^^^^SR||LEGALLAST^^^^^X~COOLNAME^AWESOMENAME2||20120605|F|||100 Main^^Lansing^MI^48912-1330^US^~^^^^^US^BDL^^123456||(517)555-2222^P^H~^PRN^PH^^^517^555-5555||en||||
         NK1||NKLast^NKFirst|MTH^3^HL70063|100 Main^^Lansing^MI^48912 1330^US^|5175555555|||||||||||||||20||||||||||30|||33^^^^SS||||37|
         ORC|||123456|
         RXA|0||20140614|20140614|83^Hepatitis A ped/adol^CVX^90633^Hepatitis A ped/adol^CPT||||00^New immunization record^NIP001|Luginbill, David|1337-44-01^Sparrow Pediatrics (Lansing)||||J005080||MSD^Merck &Co.^MVX||||A|20140614
         RXR|IM^Intramuscular^HL70162|RT^Right Thigh^HL70163
         OBX|2|CE|64994-7^Vaccine funding program eligibility category^LN||V02^VFC Eligible - Medicaid/Medicare^HL70064||||||F|||20140614
         ORC|||123456|
         RXA|0||20140614|20140614|83^Hepatitis A ped/adol^CVX^90633^Hepatitis A ped/adol^CPT||||00^New immunization record^NIP001|Luginbill, David|1337-44-01^Sparrow Pediatrics (Lansing)||||J005080||MSD^Merck &Co.^MVX||||A|20140614
         RXR|IM^Intramuscular^HL70162|RT^Right Thigh^HL70163
         OBX|2|CE|64994-7^Vaccine funding program eligibility category^LN||V02^VFC Eligible - Medicaid/Medicare^HL70064||||||F|||20140614
********************************************************
IT TOOK: 3 ms to validate
ACCEPT: ***********************************************
  - MSH-5         : MessageReceivingApplicationIsMissing[null]
  - MSH-6         : MessageReceivingFacilityIsMissing[null]
  - MSH-3         : MessageSendingApplicationIsMissing[null]
  - MSH-15        : MessageAcceptAckTypeIsMissing[null]
  - MSH-16        : MessageAppAckTypeIsMissing[null]
  - MSH-7         : MessageMessageDateIsMissing[null]
  - MSH-12        : MessageVersionIsMissing[null]
  - PID-5.3       : PatientMiddleNameIsMissing[null]
  - PID-6         : PatientMotherSMaidenNameIsMissing[null]
  - PID-5.7       : PatientNameTypeCodeIsMissing[null]
  -               : PatientPrimaryPhysicianNameIsMissing[null]
  - PD1-12        : PatientProtectionIndicatorIsMissing[null]
  - PID-3[5]      : PatientRegistryIdIsUnrecognized[22222]
  -               : PatientSystemCreationDateIsMissing[null]
  - PID-11[2].2   : PatientAddressStreet2IsMissing[null]
  - PID-11[2].9   : PatientAddressCountyIsMissing[null]
  - PID-11[2].7   : PatientAddressTypeIsMissing[null]
  -               : PatientAliasIsMissing[null]
  -               : PatientDeathIndicatorIsMissing[]
  - PID-24        : PatientBirthIndicatorIsMissing[null]
  - PV1-20.2      : PatientVfcEffectiveDateIsMissing[null]
  - RXA-21        : VaccinationActionCodeIsValuedAsAdd[A]
  - RXA-21        : VaccinationActionCodeIsValuedAsAddOrUpdate[A]
  - RXA-4         : VaccinationAdminDateEndIsMissing[null]
  - RXA-20        : VaccinationCompletionStatusIsMissing[null]
  - RXA-20        : VaccinationCompletionStatusIsUnrecognized[]
  - RXA-22        : VaccinationSystemEntryTimeIsMissing[null]
  - RXA-9         : VaccinationInformationSourceIsValuedAsAdministered[00]
  - RXA[2]-21     : VaccinationActionCodeIsValuedAsAdd[A]
  - RXA[2]-21     : VaccinationActionCodeIsValuedAsAddOrUpdate[A]
  - RXA[2]-4      : VaccinationAdminDateEndIsMissing[null]
  - RXA[2]-20     : VaccinationCompletionStatusIsMissing[null]
  - RXA[2]-20     : VaccinationCompletionStatusIsUnrecognized[]
  - RXA[2]-22     : VaccinationSystemEntryTimeIsMissing[null]
  - RXA[2]-9      : VaccinationInformationSourceIsValuedAsAdministered[00]
WARN  : ***********************************************
  - MSH-10        : MessageMessageControlIdIsMissing[null]
  - PID-13        : PatientPhoneIsIncomplete[(517)555-2222]
  - PID-13.2      : PatientPhoneTelUseCodeIsUnrecognized[P]
  - PID-13.3      : PatientPhoneTelEquipCodeIsUnrecognized[H]
  - PID-13        : PatientPhoneIsInvalid[(517)555-2222]
  - PID-3[4]      : PatientMedicaidNumberIsInvalid[33333]
  -               : PatientGuardianResponsiblePartyIsMissing[null]
  - RXA-9         : VaccinationInformationSourceIsHistoricalButAppearsToBeAdministered[null]
  - RXA[2]-9      : VaccinationInformationSourceIsHistoricalButAppearsToBeAdministered[null]
ERROR : ***********************************************
  - PID-5.2       : PatientNameFirstIsMissing[]`

**Comment by michellefbarber** [comment]
Closed per post-sprint review.
