### ISSUE TITLE
Create Unit Tests for every validation rule in validator project

### ISSUE THREAD

**Issue by JoshHull** [immregistries/mqe#44]
**[OVERVIEW]**
In order to promote the most stable and correct validation, we would like to have a JUnit test for each Rule class.  A rule class often has multiple Detections that are evaluated.  

This issue will be a high level feature set, which will have dependent MQE issues for each of the rules.  

**[REQUIREMENT]**
We need to have tests to verify that every validation is evaluated correctly.  

**[DEV NOTES]**
Some are already done.  Some will be extremely simple to test.  Some will be more complex. 

This is the full list of rules as of 3/2018: 

MessageHeaderCodesAreValid
MessageHeaderDateIsExpectedFormat
MessageHeaderDateIsValid
MessageHeaderFieldsArePresent
MessageVersionIs25
MessageVersionIsValid

NextOfKinAddressIsSameAsPatientAddress
NextOfKinAddressIsValid
NextOfKinIsPresent
NextOfKinNameIsNotSameAsPatient
NextOfKinNameIsValid
NextOfKinPhoneIsValid
NextOfKinRelationshipIsValidForUnderagedPatient

PatientAddressIsValid
PatientAliasIsValid
PatientBirthDateIsReasonable
PatientBirthDateIsValid
PatientBirthPlaceIsValid
PatientClassIsValid
PatientCodesAreValid
PatientDeathDateIsValid
PatientDeathIndicatorIsValid
PatientEthnicityIsValid
PatientExists
PatientFinancialStatusCheckTrue
PatientFinancialStatusDateIsValid
PatientGenderIsValid
PatientGuardianAddressIsValid
PatientHasResponsibleParty
PatientImmunityIsValid
PatientIsUnderage
PatientMedicaidNumberIsValid
PatientMiddleNameIsPresent
PatientMiddleNameIsValid
PatientMothersMaidenNameIsValid
PatientMultipleBirthsValid
PatientNameIsValid
PatientNameSuffixIsValid
PatientNameTypeIsValid
PatientPhoneIsValid
PatientPrimaryPhysicianNameIsValid
PatientProtectionIndicatorIsValid
PatientRegistryIdIsValid
PatientResponsiblePartyIsProperlyFormed
PatientSsnIsValid
PatientSubmitterIsValid
PatientSystemCreationDateIsValid

ObservationDateIsValid
ObservationValueTypeIsValid
VaccinationActionCodeIsValid
VaccinationAdminAfterBirthDate
VaccinationAdminCodeCptIsValid
VaccinationAdminCodeCvxIsValid
VaccinationAdminCodeIsValid
VaccinationAdminDateIsValid
VaccinationAdminDateIsValidForPatientAge
VaccinationAdministeredAmountIsReasonable
VaccinationAdministeredAmtIsValid
VaccinationAdministeredRequiredFieldsArePresent
VaccinationAdministeredUnitIsValid
VaccinationBodyRouteAndSiteAreValid
VaccinationCodeGroupsMatch
VaccinationCompletionStatusIsValid
VaccinationConfidentialityCodeIsValid
VaccinationCptIsValid
VaccinationCvxIsValid
VaccinationCvxUseIsValid
VaccinationFinancialEligibilityCodeIsValid
VaccinationInformationSourceIsValid
VaccinationIsAdministered
VaccinationIsAdministeredOrHistorical
VaccinationIsForeign
VaccinationIsPresent
VaccinationMfrIsValid
VaccinationOrdererIsValid
VaccinationProductIsValid
VaccinationRefusalReasonIsValid
VaccinationSystemEntryTimeIsValid
VaccinationUseCptInsteadOfCvx
VaccinationUseCvx
VaccinationVisCvxIsValid
VaccinationVisDatesAreValid
VaccinationVisIsPresent
VaccinationVisIsRecognized

**Comment by michellefbarber** [comment]
Issues for unit tests have been created; can this issue be closed - or do we wait for all child issues to be closed?

**Comment by michellefbarber** [comment]
Per Dev Team - ok to close since individual issues have been created.
