### ISSUE TITLE
Long file name display issue

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#53]
[Overview]
Long file names overlapping message count on the File Input screen.
![image](https://user-images.githubusercontent.com/33353164/38783525-e953da2e-40b7-11e8-99da-7f0a4a5b276c.png)

[Requirements]
File names should wrap prior to message count on File Input screen. During upload, the file name is abbreviated with ellipses - this may also be acceptable.
![image](https://user-images.githubusercontent.com/33353164/38783531-08961e10-40b8-11e8-9b08-10806f7ff5e9.png)

[Dev Notes]

[Testing]

**Comment by katelyndavis** [comment]
I'm thinking this might be fixed with a simple css update. 
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
