### ISSUE TITLE
Display issues identified in Chrome (Version 65.0.3325.181)

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#54]
[Overview]
Icons don't render - some are less relevant (e.g., graphic next to MQE Menu), but others that are descriptive are missing (e.g., trash can on File Input page, arrows to navigate dates on dashboard, etc.)
![image](https://user-images.githubusercontent.com/33353164/38783613-3fca57c4-40b9-11e8-8f4b-5551e8be3924.png)
![image](https://user-images.githubusercontent.com/33353164/38783615-4482619e-40b9-11e8-897f-309dadd9e701.png)
![image](https://user-images.githubusercontent.com/33353164/38783859-4247094e-40bd-11e8-89e3-1cf40c51b5a2.png)

[Requirements]
Need to have useful and consistent icons display. In some places, icons exist with text on button (e.g., Ack). Also consider tool tip/hover info.

[Dev Notes]

[Testing]

**Comment by michellefbarber** [comment]
Document if issue persist by OS, what causes it to display, and whether anything can be done to obviate it (e.g., browser refresh?).

**Comment by michellefbarber** [comment]
Display issues not present running on Windows using Version 66.0.3359.181 (Official Build) (64-bit).

**Comment by katelyndavis** [comment]
Is this application supposed to be ADA Compliant? If so we might need text to describe the missing images if we can't find a resolution for showing them. The need for ADA compliance might mean we need more issues to check links, tables, labels, color-contrast, etc.

**Comment by michellefbarber** [comment]
Application is not currently ADA compliant -- this issue seems to only affect Chrome on Mac (on PC works fine). Closing this issue and will open a new issue specific to ADA compliance.
