### ISSUE TITLE
Provider/PIN not pulled from message

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#56]
[Overview]
After loading files with MSH-2,3,4,5 all populated, the only option is to select MQE Unspecified from dashboard dropdown. Need to let users know where those data are coming from. Is this the right location, or is provider coming from another location in the message?
![image](https://user-images.githubusercontent.com/33353164/38783904-19fbec38-40be-11e8-964f-91434cf59c0a.png)

[Requirements]

[Dev Notes]

[Testing]

**Comment by JoshHull** [comment]
I fixed this!  

The problem was we weren't setting the facility from the message in the FileInputController.java class (even though it was set properly elsewhere)
