### ISSUE TITLE
Time of message not displaying in report

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#57]
[Overview]
Time of message not displaying when send in MSH-7 

Eg.
MSH|^~\&|M3^SENDINGAPP^OID3|M4^SENDINGFAC^OID4|M5^RECEIVINGAPP^OID5|M6^RECEIVINGFAC^OID6|**20170615084533**||VXU^V04|20170522MA53|P|2.3.1

![image](https://user-images.githubusercontent.com/33353164/38784165-ea8917f0-40c2-11e8-948f-2ce51e3f0645.png)

[Requirement]
Time should be displayed if provided. If no timestamp provided, will time default to 00:00:00?

[Dev Notes]

[Testing]

**Comment by JoshHull** [comment]
I fixed this!  

The problem was the MessageMetadata class had the field as a date, instead of timestamp. 

This will require you to either delete the database file, or run a command in the console (or put it in the schema.sql file in the project) to update the column type.
