### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by nathanbunker** [immregistries/mqe#59]
[OVERVIEW]
MQE needs a settings page that can be used to configure MQE. For now this is an open function, but later will only be allowed for MQE administrators. 

In this first iteration it will support these functions:
- Set Smarty Streets connecting information
- Enable/disable Smarty Streets
- Specify location of NIST validation tool

[REQUIREMENTS]
The Smarty Streets connecting information includes authorization ID and token. Both should be kept secret. User can set them, or see that they have been set, but should not be able to see or retrieve the set value. The user may independently enable or disable Smarty Streets. This information will be stored in the database and will override any settings provided in the validator.properties file. 

The NIST validation tool URL can also be specified, and a separate flag can be used to enable or disable it. The functionality is already present but was turned off because a local tool has to be installed in order for it to process real data. 

[DEV NOTES]
Also need to figure out process for installing the NIST tool. We should document that as well. 

[TESTING]
Should be able to have addresses verified when the right credentials are given and service is enabled. Should be able to turn it off as well, without loosing credentials. NIST validations should also be added when enabled.

**Comment by nathanbunker** [comment]
This issue was created in consequence of work in #32

**Comment by michellefbarber** [comment]
@nathanbunker and @jnarine -- Consider working on #45 to flesh out what other things need to be accommodated by this type of page.
