### ISSUE TITLE
Codes Received count error (or confusing results)

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#64]
[OVERVIEW]
On the codes received section of the report the count of (at least) address type is twice the number of records processed. Wondering if that's because in addition to counting patient address it's also counting NK1? Is it possible to change that to just patient address and limit to the value in PID-11? 

<img width="951" alt="screen shot 2018-05-04 at 2 03 26 pm" src="https://user-images.githubusercontent.com/33353164/39653056-5ed44dba-4fa4-11e8-932d-90980e7e7df0.png">

[Requirements]

[Dev Notes]

[Testing]

**Comment by nathanbunker** [comment]
Yes, it's probably reading it in both places, if it's coming in PID and NK1 then it's going to count twice. That's the problem with this list is that it's not by field, but rather it's by table. I think the right place for counting this correctly is in the section that lists the fields received.

**Comment by JoshHull** [comment]
![image](https://user-images.githubusercontent.com/10420985/40431695-f4e38bf6-5e75-11e8-9d7b-1a8b4326a086.png)

Here is the first draft solution.  Michelle, or Nathan, do you have any modifications you'd like to see done with this?

**Comment by michellefbarber** [comment]
I think this looks great -- much cleaner and clearer.
