### ISSUE TITLE
Create and document process for keeping codebase up-to-date

### ISSUE THREAD

**Issue by nathanbunker** [immregistries/mqe#73]
Create a process for keeping code base up-to-date with latest CDC codes and a communication process to release changes. Documentation on process should be visible so that the entire community can understand the steps.

**Comment by michellefbarber** [comment]
Duplicate of #68

**Comment by michellefbarber** [comment]
@nathanbunker to work with Kevin Murset

**Comment by nathanbunker** [comment]
Create a wiki page with details on the codebase and how to keep it up-to-date. I also fixed the process by which we read the codes so that it doesn't overwrite the NDC and it keeps the codes linked together properly.
