### ISSUE TITLE
MQE Demo returns -1 for RXA location problem

### ISSUE THREAD

**Issue by nathanbunker** [immregistries/mqe#81]
Go to MQE Demo, load the Example message and click Submit. The following errors show up:

```ERR||RXA^-1^3^1^1^1|101^Required field missing^HL70357|E|4^Invalid value^HL70533^MQE0261^Vaccination admin date is missing^L|||Vaccination admin date is missing null|
ERR||RXA^-1^5^1^1^1|101^Required field missing^HL70357|E|4^Invalid value^HL70533^MQE0244^Vaccination admin code is missing^L|||Vaccination admin code is missing null|
```
Note that RXA location is -1. This is probably just an extra error showing up because of changes we made to how the data was stored from the HL7 to the object.

**Comment by JoshHull** [comment]
This is fixed!

Nathan, can you verify?
