### ISSUE TITLE
Message Information - Segment Filter off by 1

### ISSUE THREAD

**Issue by katelyndavis** [immregistries/mqe#84]
[Overview]
When looking at the individual message information page, the segment filter is off by 1. The selected segment filters the message by the the segment above it. 

[Requirements]
On the Message Information page, the selected segment should filter on the selected segment.

[Dev Notes]
![image](https://user-images.githubusercontent.com/37371748/43483996-2de02c02-94db-11e8-9dfc-80f27ed54702.png)
![image](https://user-images.githubusercontent.com/37371748/43484043-406b4992-94db-11e8-940c-f082a70f7e03.png)

[Testing]
Click on the segment button to the right of the table. 
Click on the segment in the message received textarea.

**Comment by JoshHull** [comment]
Fixed!

This issue was caused by the indexing change we did in HL7-Util.  We are using a 1 based index for the message locations. 

The file I fixed it in was message-detail.html: 

                                ng-click="toggleTab($index+1);"
                                ng-class="{active: $index===current.segment-1}">
