### ISSUE TITLE
Add Completeness for vaccine type to report

### ISSUE THREAD

**Issue by michellefbarber** [immregistries/mqe#9]
[OVERVIEW]
The Vaccine Group section needs to display by age. This may solve the issue   of templates. In DQA v1.5 the idea was to have templates for Pharmacies vs   Family Practice vs Hospital. The idea is that the different types of practice   might give different types of vaccinations. But it was pointed out that if we   could simply organize the Vaccine Groups by age then it would be easy to see   what was there and what is missing, and would solve a lot of the problem.   There would still be a gap for situations where the facility provides care   for a particular age but doesn't give a full complement of vaccines.   Pharmacies might be a good example of this problem. We may still need   templates for this, but this story will not include that.

[REQUIREMENTS]
[Break it down into components, but it is still oriented around business   requirements, UI/DBB/Fields]      Report for vaccine groups should be broken down into   age bands (TBD). The total score should be based on how complete each age   band is.

[DEV NOTES]
[where devs note stuff to each other to give help on how to get   started]

[TESTING]
[how to verify it's done.  A lot of it   is repeat of the req section, and may refer to it]

**Comment by michellefbarber** [comment]
04/Dec/17   7:55 AM;j.hull;Discussed with Nathan this morning. 
The things we need:
Codebase:
1. Vaccine groups (already there) 
2. What age range is expected for a group.  (we know what's expected for a specific   vaccine, but as a group it will be wider). 

DQA Model: 
1. Age/group count
2. Report   definition - perhaps we can use this to determine categories.  Shows what we think the site is. 

There are two things we need to report on:
1. Are   the vaccines sent for the right ages. The data necessary is already there for   that. 
2. Are all of the types expected for this type of provider being sent.   Trying to find the ones they're missing. This is the big money item, but we   need the support of the previous item.

Start of #2 might be: "for the ages of people you've sent, here are the   groups you're missing during this time period."             Then we might get more advanced with scoring and categorizing.

**Comment by michellefbarber** [comment]
05/Dec/17   7:48 AM;admin; 

I just attached a file to this task showing a potential   classification for vaccine groups by patient age. I used as my source the CDC   quick recommendation sheets that lists which vaccinations should be given to   people at what ages.             

At this point I think we can set the following things:            
*Fixed Age Groups*      
The age groups should be fixed nationally. I see 5 major groups:      
* Infants (<1)      
* Children (1-6)      
* Teens (7-18)      
* Adults (19-59)      
* Older Adults (60+)            

For each age group and each vaccine group one of the following statuses can   be assigned:      
* Expected: The vaccination should often be   administered for this age group      
* Possible; The vaccination sometimes is given for this age group, not   particularly noteworthy when given      
* Not Expected: The vaccine should never be given to this age group,   or is rarely given to this age group, or should be noted and reviewed if   given to this age group.      
* Ignore: The vaccine group should just be ignored (usually because it's   covered by a more representative group)            

What important to note here is that this system does not try to replicate   exactly when a vaccination is valid to give and when it is not. Rather it's a   measure of what we generally expect. So for this reason there are perfectly   valid vaccines that we may list as "Not Expected" only because they   are rarely given. The validation of the right age and right vaccine is   already handled by other methods. This is just to give a high level check to   what is being coded.

**Comment by nathanbunker** [comment]
Some progress is being made but the final vision is not there yet. Probably need to put the concepts that drive this in the code management project, not as another set of codes, but rather as a set of codes that are needed for the report.

**Comment by nathanbunker** [comment]
Information is coming back but the complete vision of where this should go is not complete. Closing this issue and we need to get more feedback from the community to make a new ticket.
