### ISSUE TITLE
DAR-10 Need Verification

### ISSUE THREAD

**Issue by nathanbunker** [immregistries/mqe#94]
The following detections need verification they are implemented and working.  If they are not, they need to be implemented. Sorry, I ran out of time on looking at the code to see if these are implemented and work

- MQE0533: Patient has junk name - MQE Code not assigned
                                                            - Found As **MQE0173**
- MQE0140: Patient first name is invalid - **Implemented**
- MQE0165: Patient last name is invalid - **Implemented**
- MQE0175: Patient phone is invalid - **Implemented**
- MQE0562: Patient Address is invalid - **Implemented**
- MQE0120: Birth date is a long time ago - **Implemented**
- MQE0309: CVX unrecognized - **Implemented**
- MQE0344: MVX unrecognized - **Implemented**
- MQE0284: Site unrecognized - **Implemented**
- MQE0278: Route unrecognized - **Implemented**

I also have a bunch of MISSING detections that need to work, but I’m hoping those are pretty standard in their implementation. I did add two below which I couldn’t find the data element concept.

**Comment by HossamT** [comment]
See original issue edited.
